apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coco-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    hello: world
spec:
  tls:
    - hosts:
      - hrvojetonkovac.from.hr
      secretName: tls-certs-hrvojetonkovac.from.hr
  rules:
  - host: hrvojetonkovac.from.hr
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend-service
          servicePort: 80
      - path: /backend-1-service(/|$)(.*)
        backend:
          serviceName: backend-1-service
          servicePort: 80