# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: coco-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/use-regex: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: $1

# spec:
#   rules:
#   - host: "*.com"
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: frontend-service
#           # serviceName: backend-1-service
#           servicePort: 80
#       - path: /backend-1-service(.*)
#         backend:
#           serviceName: backend-1-service
#           servicePort: 80

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: test.com
    http:
      paths:
      - path: /foo/.*
        backend:
          serviceName: test
          servicePort: 80