apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-1.yaml
  - frontend.yaml
  - ingress.yaml
  - clusterIssuer-staging.yaml
  - clusterIssuer-prod.yaml


secretGenerator:
- name: rds-conn-details
  env:  environment.env
  type: Opaque

